In [1]:
options(warn = -1)
options(repr.plot.width = 15, repr.plot.height = 9)
Sys.setlocale(category = "LC_ALL", locale = "ko_KR.UTF-8")

[1] "ko_KR.UTF-8/ko_KR.UTF-8/ko_KR.UTF-8/C/ko_KR.UTF-8/C.UTF-8"

#조건문

In [2]:
x <-10
y <- runif(1) * 100
################
if(x > y){
    print("x > runif()")
    print("x가 큽니다.")
}else if(x<y){
    print("x<runif()")
    print("x가 작습니다.")
}else{
    print("x=runif()")
    print("x와 같습니다.")
}
#################
#[]번째다.->cat

[1] "x<runif()"
[1] "x가 작습니다."

#홀짝수 구분

In [3]:
a <- 8
if(a%%2==0){
    cat(a,"는 짝수 입니다.\n")
}else{
    cat(a,"는 홀수 입니다.\n")
}
#스칼라 없음 : 벡터
#리스트 처리 못함

8 는 짝수 입니다.

In [4]:
a <- c(8, 10, 11)#반복이 있는 삼항연산자
ifelse(a%%2==0,"짝수","홀수")

[1] "짝수" "짝수" "홀수"

In [5]:
#a <- c(8, 10, 11)#반복이 있는 삼항연산자
#ifelse(a%%2==0,cat(a ,":짝수"),cat(a,":홀수"))

In [6]:
a <- c(8, 10, 11)
ifelse(a%%2==0,paste(a ,":짝수"),paste(a,":홀수"))

[1] "8 :짝수"  "10 :짝수" "11 :홀수"

In [7]:
a <- c(8, 10, 11)#paste:벡터 만드는 함수
cat(ifelse(a%%2==0,paste(a ,":짝수"),paste(a,":홀수")))

8 :짝수 10 :짝수 11 :홀수

#readline(input)

In [8]:
num1 <- readline("숫자를 입력하세요:")
num1
class(num1)#문자:암호화 하기위해

[1] "11"

[1] "character"

In [9]:
num1 <- as.integer(readline("숫자를 입력하세요:"))
num1
class(num1)

[1] 66

[1] "integer"

In [10]:
#사용자로 부터 점수를 입력받아 학점으로 변경하여 출력하기
score_input <- readline("점수를 입력하세요:")
score <- as.numeric(score_input)
if(score>=90){
    cat("A")
}else if(score>=80){
    cat("B")
}else if(score>=70){
    cat("C")
}else if(score>=60){
    cat("D")
}else{
    cat("F")
}

F

In [11]:
#csv file 불러 처리
excel <- read.csv("../Data/excel.csv")
head(excel)

  q1 q2 q3 q4 q5
1 2  4  4  2  2
2 1  2  2  2  2
3 2  3  4  3  3
4 3  5  5  3  3
5 3  2  4  4  4
6 4  3  3  4  2

In [12]:
str(excel)#struct구조402개,컬럼5개

'data.frame':	402 obs. of  5 variables:
 $ q1: int  2 1 2 3 3 4 3 4 4 4 ...
 $ q2: int  4 2 3 5 2 3 4 2 4 2 ...
 $ q3: int  4 2 4 5 4 3 4 4 5 4 ...
 $ q4: int  2 2 3 3 4 4 2 4 3 2 ...
 $ q5: int  2 2 3 3 4 2 2 4 4 3 ...

In [13]:
#q1 컬럼으로 data가 3보다 크거나 같으면 data의 제곱근을 구하고 아니면 원래 data 출력하기
q1 <- excel$q1
length(q1)
ifelse(q1>=3,sqrt(q1),q1)

[1] 402

  [1] 2.000000 1.000000 2.000000 1.732051 1.732051 2.000000 1.732051 2.000000
  [9] 2.000000 2.000000 2.000000 1.732051 1.732051 1.732051 1.000000 1.732051
 [17] 1.732051 1.732051 2.000000 1.732051 1.732051 2.000000 2.000000 2.000000
 [25] 1.732051 2.000000 2.000000 2.000000 1.732051 1.732051 1.000000 1.732051
 [33] 1.732051 1.732051 2.000000 1.732051 2.000000 2.000000 1.732051 2.000000
 [41] 2.000000 2.000000 1.732051 1.732051 2.000000 2.000000 2.000000 1.000000
 [49] 2.000000 1.732051 2.000000 2.000000 1.732051 2.000000 1.732051 2.000000
 [57] 2.000000 2.000000 2.000000 1.732051 2.000000 2.000000 2.000000 1.732051
 [65] 1.732051 1.732051 1.732051 2.000000 1.000000 2.000000 1.732051 1.732051
 [73] 1.732051 2.000000 2.000000 2.000000 1.000000 1.732051 1.732051 2.000000
 [81] 2.000000 2.000000 1.732051 2.000000 1.732051 1.732051 2.000000 1.732051
 [89] 2.000000 2.000000 2.000000 2.000000 2.000000 2.000000 1.000000 2.000000
 [97] 2.000000 2.000000 2.000000 2.000000 1.732051 1.732051 2.000000 1.732051
[105] 1.732051 2.000000 2.000000 2.000000 2.000000 2.000000 2.000000 2.000000
[113] 1.732051 2.000000 2.000000 2.000000 1.732051 1.732051 1.732051 2.000000
[121] 1.000000 1.732051 2.000000 1.732051 1.732051 2.000000 1.732051 1.732051
[129] 1.732051 2.000000 2.000000 2.000000 1.000000 1.732051 1.732051 2.000000
[137] 1.732051 2.000000 1.732051 1.000000 2.000000 1.732051 2.236068 2.000000
[145] 1.732051 1.732051 2.000000 2.000000 1.732051 2.000000 1.732051 1.732051
[153] 1.000000 1.732051 2.000000 2.000000 1.732051 1.732051 2.000000 2.000000
[161] 2.000000 2.000000 2.000000 2.000000 1.732051 1.732051 1.732051 2.000000
[169] 2.000000 2.000000 1.000000 1.732051 1.732051 2.000000 1.732051 2.000000
[177] 1.732051 1.000000 2.000000 1.732051 2.236068 2.000000 1.732051 1.732051
[185] 2.000000 2.000000 1.732051 2.000000 1.732051 1.732051 1.000000 1.732051
[193] 2.000000 2.000000 2.000000 2.000000 2.000000 2.000000 2.000000 1.732051
[201] 2.000000 2.000000 2.000000 1.732051 1.732051 1.732051 2.000000 1.000000
[209] 1.732051 2.000000 1.732051 1.732051 2.000000 1.732051 1.732051 1.000000
[217] 1.732051 1.732051 2.000000 1.732051 2.000000 1.732051 1.000000 2.000000
[225] 1.732051 2.236068 2.000000 1.732051 1.732051 2.000000 2.000000 1.732051
[233] 2.000000 1.732051 1.732051 1.000000 1.732051 2.000000 2.000000 1.732051
[241] 1.732051 2.000000 2.000000 2.000000 2.000000 2.000000 2.000000 1.732051
[249] 1.000000 1.732051 2.000000 2.000000 2.000000 2.000000 2.000000 2.000000
[257] 2.000000 1.732051 2.000000 2.000000 2.000000 1.732051 1.732051 1.732051
[265] 2.000000 1.000000 1.732051 2.000000 1.732051 1.732051 2.000000 2.000000
[273] 1.732051 2.000000 1.732051 1.732051 1.000000 1.732051 2.000000 2.000000
[281] 1.732051 1.732051 2.000000 2.000000 2.000000 2.000000 2.000000 2.000000
[289] 1.732051 1.000000 1.732051 2.000000 2.000000 2.000000 2.000000 2.000000
[297] 2.000000 2.000000 1.732051 2.000000 2.000000 2.000000 1.732051 1.732051
[305] 1.732051 2.000000 1.000000 1.732051 1.732051 2.000000 2.000000 1.732051
[313] 2.000000 1.732051 1.732051 1.000000 1.732051 2.000000 2.000000 1.732051
[321] 1.732051 2.000000 2.000000 2.000000 2.000000 2.000000 2.000000 1.732051
[329] 1.000000 1.732051 2.000000 2.000000 2.000000 2.000000 2.000000 2.000000
[337] 2.000000 1.732051 2.000000 2.000000 2.000000 1.732051 1.732051 1.732051
[345] 2.000000 1.000000 2.000000 1.732051 1.732051 1.000000 1.732051 2.000000
[353] 2.000000 1.732051 1.732051 2.000000 2.000000 2.000000 2.000000 2.000000
[361] 2.000000 1.732051 1.000000 1.732051 2.000000 2.000000 2.000000 2.000000
[369] 2.000000 2.000000 2.000000 1.732051 2.000000 2.000000 2.000000 1.732051
[377] 1.732051 1.732051 2.000000 1.000000 1.732051 2.000000 1.732051 1.732051
[385] 2.000000 2.000000 1.732051 2.000000 1.732051 1.732051 1.000000 1.732051
[393] 2.000000 2.000000 1.732051 1.732051 2.000000 2.000000 2.000000 2.000000
[401] 2.000000 2.000000

In [14]:
q1 <- excel$q1
length(q1)
excel$q6<-ifelse(q1>=3,sqrt(q1),q1)
head(excel)

[1] 402

  q1 q2 q3 q4 q5 q6
1 2  4  4  2  2  2.000000
2 1  2  2  2  2  1.000000
3 2  3  4  3  3  2.000000
4 3  5  5  3  3  1.732051
5 3  2  4  4  4  1.732051
6 4  3  3  4  2  2.000000

In [15]:
#score가 80점이상이면 우수, 아니면 노력이라고 출력하기
score = c(78,85,95,65,100)
ifelse(score>=80,"우수","노력")

[1] "노력" "우수" "우수" "노력" "우수"